apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://akshci-monitoring-cluster2-prometheus.monitoring:9090
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 30s